s3domain = ["s3.test.com", "s3-internal.test.com"]
log_level = "info"
log_path = "/var/log/pipa/pipa.log"
workers_number = 64
max_task_number = 10000

redis_address = "redis:6379"
redis_password = "hehehehe"
redis_connect_timeout = 5
redis_read_timeout = 5
redis_write_timeout = 5
redis_pool_max_idle = 300
redis_pool_idle_timeout = 30
